### PR TITLE
Add support for android support library 23.1.1

### PR DESCRIPTION
**Pull request by fernandodev**
- android.support.v7.internal.* was moved to android.support.v7.*
- now it's necessary to explicit attrs for `android:prompt` and `android:disableChildrenWhenDisabled`
- improve gradle build system with shared `compile target` and `build tools` values

### CODE REVIEW

**Comment by andrewpros** [comment]
There were no commits since months, is there a better, supported fork?

**Comment by AppDev666** [comment]
thanks that save my life.

**Comment by AppDev666** [comment]
@andrewpros  check
https://github.com/fernandodev/material/commit/bc14c21bef31aa734f300710ec08baf380f12fc3

**Comment by andrewpros** [comment]
@AppDev666 Yeah i know, but i want a gradle workflow, the author have not even time to marge pulls and make new release, then this project is really dead.

**Comment by fernandodev** [comment]
https://github.com/rey5137/material/releases/tag/1.2.2

**Pull request closed without merging**
